### ISSUE TITLE
Document anon

### ISSUE THREAD

**Issue by rom1504** [ProtoDef-io/ProtoDef#21]

**Comment by AntiCheap** [comment]
Yes please, issue still present. Trying to understand this I got even more confused.

<details><summary>What I tested.</summary>
<p>

```json
[
    {
        "name": "value",
        "type": "i8"
    },
    {
        "anon": true,
        "type": [
            "switch",
            {
                "compareTo": "value",
                "fields": {
                    "-1": "i8"
                },
                "default": [
                    "container",
                    [
                        {
                            "name": "a",
                            "type": "u8"
                        },
                        {
                            "name": "b",
                            "type": "u8"
                        }
                    ]
                ]
            }
        ]
    }
]
```

</p>
</details>

<details><summary>How it was evaluated</summary>
<p>

```js
(buffer, offset) => {
    const { value: value1, size: value1Size } = (ctx.i8)(buffer, offset);
    const { value: a, size: aSize } = ((buffer, offset) => {
        switch (value1) {
            case -1: return (ctx.i8)(buffer, offset);
            default: return (ctx.u8)(buffer, offset);
        }
    })(buffer, offset + value1Size);
    const { value: b, size: bSize } = ((buffer, offset) => {
        switch (value1) {
            case -1: return (ctx.i8)(buffer, offset);
            default: return (ctx.u8)(buffer, offset);
        }
    })(buffer, offset + value1Size + aSize);
    return { value: { value: value1, a, b }, size: value1Size + aSize + bSize };
}
```

What code I belive I should've written to get that result:

```json
[
    {
        "name": "value",
        "type": "i8"
    },
    {
        "name": "a",
        "type": [
            "switch",
            {
                "compareTo": "value",
                "fields": {
                    "-1": "i8"
                },
                "default": "u8"
            }
        ]
    },
    {
        "name": "b",
        "type": [
            "switch",
            {
                "compareTo": "value",
                "fields": {
                    "-1": "i8"
                },
                "default": "u8"
            }
        ]
    },
]
```

</p>
</details>

### Actual problems:
- The comparison could've been done just once.
- An anonymous switch can hold fields with no name.
- Void is meaningful only inside switch.

This seems "negligible" but stating that anonymous switch can only include types void or container can improve clarity and parsing code. I don't think it's ever useful to give to all the elements in a containers another type (outside for void).

**Comment by rom1504** [comment]
> The comparison could've been done just once.

yes it's not completely optimal (maybe?) in node protodef compiler implementation. You can do the comparison only once if you want.

> An anonymous switch can hold fields with no name.

no it cannot, this unspecified behavior and in this case node protodef is doing something that doesn't make a lot of sense

> Void is meaningful only inside switch.

there is no void in your example?

> This seems "negligible" but stating that anonymous switch can only include types void or container can improve clarity and parsing code.

yes or things that produce something like a container. Maybe you could check all the uses of them in mc protocol, and if it turned out it's only switch + container, we could decide to add that to the spec ?
