### ISSUE TITLE
Questions about endianness

### ISSUE THREAD

**Issue by nickelpro** [ProtoDef-io/ProtoDef#28]
Two questions:

- Are all the "normal" numeric types (i16, u16, i32, u32, etc) big-endian? In minecraft-data they're definitely used this way and the existence of little-endian types implies this, but it doesn't seem to be explicitly written down anywhere

- Why do the li8 and lu8 types exist? Bit-level endianness isn't usually a thing and they can only lead to confusion.

**Comment by roblabla** [comment]
- the default types are big-endian, as that's what the default network order is. Sending stuff in little endian over the network is unusual in most standard protocol. For those cases, the li/lu famility of types exist. It definitely should be mentioned somewhere!

- li8/lu8 exist only for symmetry. They map down to the same type.

**Comment by nickelpro** [comment]
Thanks I understand about network order, I'm writing a quick&dirty protodef to C compiler and just wanted to make sure I wasn't missing anything. I still recommend describing the endianness somewhere in the datatypes doc. I think supporting various endian 1-byte types is strange but it's not my project.

Thanks again for the clarifications.
