### ISSUE TITLE
Bitfield type in everything that isn't Javascript

### ISSUE THREAD

**Issue by nickelpro** [ProtoDef-io/ProtoDef#29]
The bitfield type defines its size implicitly, and this is a massive PITA.
The natural solution for encoding/decoding a bit mask in many languages is something like this:
```C
char *my_decode_function(some_struct *dest, char *source) {
  uint32_t bitmask;
  source = decode_uint32(&bitmask, source);
  dest->value_A = bitmask&0xFF;
  dest->value_B = bitmask>>8;
  return source;
}
```

Generating this code from a protodef is incredibly annoying because you have to parse the bitfield twice. Once just to get its size, select the correct type, and generate code for it. Then a second time to generate the code for the whatever embedded flags/values there are.

Also, implicit deceleration is inflexible. Many times a bitmask will be declared a certain size, but only some of the bits will have a purpose, the the remaining being reserved or just unused. I recommend bitfields be changed to require an explicit size deceleration. and then the follow on bitmap.

**Comment by roblabla** [comment]
I don't totally agree. For starters, your decode function is wrong for the general case. A bitfield can be bigger than an u32 or an u64, e.g. when dealing with bitfield structs. The switch IPC format (which I use protodef to decode) loooooves those. To give an example:

```
struct test {
     uint16_t val1: 10;
     uint16_t val2: 10;
     uint16_t val3: 10;
     uint16_t val4: 10;
     uint16_t val5: 10;
     uint16_t val6: 10;
     uint16_t val7: 10;
     uint16_t val8: 10;
     uint16_t val9: 10;
}
```

this is encoded on 12 bytes (if my maths aren't incorrect). You won't be able to just "decode_uint32" your way out of this. You need to actually read those 12 bytes, and then get the bits as you go. (You can also be a bit more "streamy" and only get bytes in pair, but you get the idea).

Now, if your suggestion is to change bitfield to:

```
["bitfield", [12, [
      { "name": "val1", "size": 10, "signed": false },
      ...
]]]
```

I can somewhat understand why you'd want this, buuuut... Part of me would prefer to just enforce that the sum of the "size" bits should be divisible by 8. You'd have to explicitly state the remaining padding. This is to avoid a situation where there are conflicting source of truths when manually editing a JSON.

**Comment by roblabla** [comment]
> Also, implicit deceleration is inflexible.

Can you explain what you mean by that? For me, the current format has the most flexibility. There's nothing you can't express with the current bitfield format.

**Comment by nickelpro** [comment]
From minecraft-data:
```json
[
  "bitfield",
  [
    { "name": "_unused", "size": 29, "signed": false },
    { "name": "hidden", "size": 1, "signed": false },
    { "name": "show_toast", "size": 1, "signed": false },
    { "name": "has_background_texture", "size": 1, "signed": false }
  ]
]
```

Because we aren't explicit about the size of the bitfield the "_unused" field has to be added. Protodef doesn't define a specific way to include the padding necessary to make this kind of bitfield work, so each protocol has to come up with their own hack and a compiler has to understand each hack in order to not decode worthless fields.

A more correct way to do this would to be explicit about the overall size of the bitmask, as well as the offset and size of each field. It would look something like this:

```json
[
  "bitfield",
  "u32"
  [
    { "name": "hidden", "size": 1, "offset": 2, "signed": false },
    { "name": "show_toast", "size": 1, "offset": 1, "signed": false },
    { "name": "has_background_texture", "size": 1, "offset": 0, "signed": false }
  ]
]
```

The inclusion of the offset is also one less thing the compiler has to calculate in the first pass.

**Comment by nickelpro** [comment]
Thinking about it more, you could achieve both by just being explicit about the number of bytes in the header of the type and then still doing the size/offset (in bits) for each field. So instead of "u32" just do this:

```json
[
  "bitfield",
  4
  [
    { "name": "hidden", "size": 1, "offset": 2, "signed": false },
    { "name": "show_toast", "size": 1, "offset": 1, "signed": false },
    { "name": "has_background_texture", "size": 1, "offset": 0, "signed": false }
  ]
]
```

Your example of a bunch of 10-bit values mapped over 12 bytes would work like this.

```json
[
  "bitfield",
  12
  [
    { "name": "value_A", "size": 10, "offset": 0, "signed": false },
    { "name": "value_B, "size": 10, "offset": 10, "signed": false },
    { "name": "value_C", "size": 10, "offset": 20, "signed": false }
  ]
]
```

Note that I reversed the order of the offsets, this format doesn't have any ordering requirement meaning fields can be encoded in whatever feels natural for the type, and you still don't have to do any padding hacks.
