### ISSUE TITLE
remove int and lint ?

### ISSUE THREAD

**Issue by rom1504** [ProtoDef-io/ProtoDef#34]
Any reason to have added them @Saiv46 ? we never needed that
If no reason, I'll remove them
(cc @roblabla )

**Comment by roblabla** [comment]
I don't see lint anywhere? Anyways int can certainly go, it's redundant with i8 and family. I don't see much point to it, I doubt any network app sends flat numerics of sizes other than those defined (I'd be happy to be proven wrong though!)
