### ISSUE TITLE
Add little endian numerical types

### ISSUE THREAD

**Issue by rom1504** [ProtoDef-io/ProtoDef#4]
Because we need them for mcpe nbt. (Yes mojang will use everything that's usable)

Also I believe these are generally usable so they belong in protodef.

Name proposal: li32 and lu32. Any better idea for the names ?

**Comment by rom1504** [comment]
Idk if it would make sense and how but maybe there should be a big option somewhere to switch between little endian and big endian without having to rewrite the json definition.
It would be useful since mcpe nbt is exactly the same as mcpc nbt except for little endian.

**Comment by rom1504** [comment]
I think that should probably just be a package that transform the types json from one endianness to the other. Let's keep it simple from protodef point of view.

**Comment by mhsjlw** [comment]
Why convert it? Like you said earlier,
> a big option somewhere to switch between little endian and big endian

I think that that's the best solution as, when more people start to use ProtoDef on ARM and x86 devices (maybe even mobile once we get more language support?) they need this feature, and they shouldn't have to convert an entire project to use it.

**Comment by hansihe** [comment]
If we do that, we remove the ability to make parts of a protocol big endian and other parts little endian, we lose flexibility.

Whether a specific field is little or big endian should be rigidly defined by the protocol. If a different variant of a protocol has different endianness, it's not protodefs job to make that adaptation, the protocol definition file should be changed (could be done automatically without any problems). If we add a global endianness toggle, we are adding specialization to protodef just to make our lifes easier with that one protocol. I would prefer if we kept protodef as a tool as general as possible.

**Comment by rom1504** [comment]
Yes I agree with hansihe, that's what I meant to say in my last comment.
There are indeed some protocols with both little and big endian (I'm not
100% sure but I think I remember that raknet has some of that with the
triad types)

**Comment by rom1504** [comment]
done at 5dbfbf74d1a30b508eb314f4c4275f8139d43371

It might be needed to add more little endian types, idk how string and array are handled in little endian. I'll add more issues/commits if needed when we make prismarine-nbt work in little endian.
