### ISSUE TITLE
Question on implementation

### ISSUE THREAD

**Issue by MyUsernamee** [ProtoDef-io/ProtoDef#45]
Hi! I am trying to implement the protodef specification in rust! I am slightly confused on how all of the datatypes relate to the structure of the final program. 

For example:

If I passed this protodef:
```
{
  "types": {
    "varint": "native",
    "test": "varint"
  }
}
```
to a theoretical Rust Protodef compiler what would it result in?

I think it is just supposed to create a second struct with a varint field like:
```
struct test {
    
    varint: varint,
    
}
// Serialize and Desalinize methods not shown.
```
but I am unsure of this though.

Sorry if this is a dumb question.
Thank you so much in advance!

**Comment by rom1504** [comment]
Protodef high level type dictionary declare types with how to read and
write them.

"Native" types are types that are assumed to be already implemented with
native code (eg rust for you)

For the example here you would have a varint type and a test type

You can look at node-protodef for an example of implementation
